language: ruby
sudo: false
rvm:
  - 2.4
services:
  - mysql
  - redis-server
addons:
  apt:
    packages:
      - libmagic-dev
  chrome: stable
env: COVERALLS=1
cache: bundler
bundler_args:
  - "--without development --deployment --jobs=3 --retry=3"
before_script:
  - "bundle exec rake foodsoft:setup:stock_config"
  - "mysql -e 'create database foodsoft_test default character set utf8 default collate utf8_general_ci;'"
  - "mysql -e 'grant all on foodsoft_test.* to travis;'"
  - 'printf "test:\n  adapter: mysql2\n  database: foodsoft_test\n  username: travis\n  encoding: utf8\n" >config/database.yml'
  - 'bundle exec rake db:schema:load RAILS_ENV=test'
script: bundle exec rake rspec-rerun:spec
