version: '2'
services:

  foodsoft:
    extends: foodsoft_worker
    command: ./proc-start web
    ports:
      - "3000:3000"

  foodsoft_worker:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: ./proc-start worker
    volumes:
      - bundle:/home/app/bundle
      - .:/home/app/src
    environment:
      - DATABASE_URL=mysql2://root:secret@mariadb/development?encoding=utf8
      - REDIS_URL=redis://redis:6379
      - QUEUE=foodsoft_notifier
      - TEST_DATABASE_URL=mysql2://root:secret@mariadb/test?encoding=utf8
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - "1080:80"

  mariadb:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mariadb:/var/lib/mysql

  redis:
    image: redis:3.2-alpine

volumes:
  bundle:
  mariadb:
